# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.



name: Charlotte Ruby User Group
baseurl: "" # the subpath of your site, e.g. /blog
description: >- # this means to ignore newlines until "baseurl:"
  A friendly group of Ruby programmers around the Charlotte metro area!
disqus: 'demowebsite'
email: team@charlotte-ruby.org
favicon: 'assets/images/favicon.ico'
github_username: charlotte-ruby
logo: 'assets/images/logo.png'
mailchimp-list: ''
permalink: /:title/
title: Charlotte Ruby User Group
twitter_username: cltrb
url: "http://charlotte-ruby.github.io"

include: ["_pages"]

authors:
    matt:
      name:           Matt McMahand
      site:           https://invalid8.com
      avatar:         https://en.gravatar.com/userimage/3816903/d99228112ca91cbe242fbcabcc11c96c.jpeg
      bio:            I'm a software engineer who likes creating problems almost as much as I like solving them
      email:          matt@invalid8.com
      twitter:        https://twitter.com/invalidusrname
    charlotte-ruby:
      name:           Charlotte Ruby
      site:           https://charlotte-ruby.github.io
      avatar:         https://en.gravatar.com/userimage/3816903/292c15ab4ab0ecf1b438dcdb2a041354.png
      bio:            I'm the Charlotte Ruby bot!
      twitter:        https://twitter.com/cltrb

# Build settings
theme:
plugins:
  - jekyll-archives
  - jekyll-feed
  - jekyll-seo-tag
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

defaults:
  - scope:
      path: "_posts"
    values:
      layout: post
      author: charlotte-ruby
      avatar: https://en.gravatar.com/userimage/3816903/292c15ab4ab0ecf1b438dcdb2a041354.png
  - scope:
      path: "_pages"
    values:
      layout: page
# Syntax
markdown: kramdown
highlighter: rouge

paginate: 10

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
